name        "artifakt"
description "Artifakt Opsworks Recipes"
maintainer  "Artifakt"
license     "Apache 2.0"
version     "1.0.0"

depends "artifakt_cloudwatchagent"

depends "mod_php5_apache2"
depends "php"
depends "deploy"
depends "apache2"
depends "php-fpm"
depends "nginx"
depends "mysql"
depends "artifakt_composer"
depends "artifakt_crontab"
depends "artifakt_efs"
depends "artifakt_htpasswd"

depends "artifakt_certificates"
depends "artifakt_runtime_config"

depends "artifakt_app_akeneo"
depends "artifakt_app_drupal"
depends "artifakt_app_magento"
depends "artifakt_app_magento2"
depends "artifakt_app_orocommerce"
depends "artifakt_app_orocrm"
depends "artifakt_app_shopware"
depends "artifakt_app_phpapp"
depends "artifakt_app_sylius"
depends "artifakt_app_symfony"
depends "artifakt_app_wordpress"

depends "artifakt_logs"
depends "artifakt_sftp_users"
depends "ssh_users"
depends "artifakt_docker"
depends "artifakt_elasticsearch"
depends "artifakt_rabbitmq"
depends "artifakt_supervisor"
depends "artifakt_redis"
depends "artifakt_quanta"
depends "artifakt_newrelic"
depends "artifakt_varnish"

recipe "artifakt::setup", "Setup an Application by Artifakt"
recipe "artifakt::configure", "Configure an Application by Artifakt"
recipe "artifakt::deploy", "Deploy an Application by Artifakt"
recipe "artifakt::undeploy", "UnDeploy an Application by Artifakt"
recipe "artifakt::shutdown", "Shutdown an Application by Artifakt"
recipe "artifakt::install", "Install an Application by Artifakt"
