version: "3"
services:
  elasticsearch:
    container_name: es
    build: .
    restart: always
    ports:
      - 9200:9200
      - 9300:9300
    volumes:
      - /mnt/shared/elasticsearch:/usr/share/elasticsearch/data
    environment:
      - node.name=es01
      - bootstrap.memory_lock=true
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
