###
# This is the place to override the apache2 cookbook's default attributes.
#
# Do not edit THIS file directly. Instead, create
# "apache2/attributes/customize.rb" in your cookbook repository and
# put the overrides in YOUR customize.rb file.
###

default[:apache][:version]       = "2.4"
default[:apache][:group]       = 'opsworks'
default[:apache][:prefork][:startservers] = 64
default[:apache][:prefork][:minspareservers] = 64
default[:apache][:prefork][:maxspareservers] = 128
default[:apache][:prefork][:maxrequestsworkers] = 50
default[:apache][:timeout] = 300
default[:apache][:keepalive] = 'Off'
default[:apache][:logrotate][:rotate] = '7'
default[:apache][:custom][:encodedslashes] = false

default[:app][:language_long] = '5.6'
default[:app][:language] = '56'

