###
# This is the place to override the opsworks_initial_setup cookbook's default attributes.
#
# Do not edit THIS file directly. Instead, create
# "opsworks_initial_setup/attributes/customize.rb" in your cookbook repository and
# put the overrides in YOUR customize.rb file.
###

# The following shows how to override OpsWorks default TCP keepalive timeout:
#
#normal[:opsworks_initial_setup][:sysctl]['net.ipv4.tcp_keepalive_time'] = 2048

default['opsworks_initial_setup']['swapfile_instancetypes'] = [ 't1.micro', 't2.micro', 't2.small', 't2.medium', 'c4.large' ]
default['opsworks_initial_setup']['swapfile_name'] = '/var/swapfile'
default['opsworks_initial_setup']['swapfile_size_mb'] = 1536